project:
  type: website
  output-dir: docs

website:
  title: "Arnau Garcia-Fernández"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - software.qmd
      - talks.qmd
      - cv.qmd

  page-footer:
    left: |
      © 2026 Arnau Garcia-Fernández

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
